copyright = "© Senne"
defaultContentLanguage = "en"
disableKinds = ["taxonomy"]
enableRobotsTXT = true
languageCode = "en"
timeZone = "Europe/Brussels"
timeout = "120s"
title = "Gallery"
theme = "gallery"

[params]
  defaultTheme = "dark"
  description = "My Photo Gallery"
  title = "My Gallery"
  [params.author]
    name = "Senne"

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML"]

[imaging]
  quality = 75
  resampleFilter = "CatmullRom"
  [imaging.exif]
    disableDate = false
    disableLatLong = true
    includeFields = "ImageDescription|Orientation"

[services]
  [services.rss]
    limit = 100
